package high_iq

IQ_EN_CURSOR :: ">"
IQ_EN_GAME :: "GAME"
IQ_EN_MODE :: "MODE"
IQ_EN_NORMAL :: "NORMAL"
IQ_EN_ORIGINAL :: "ORIGINAL"
IQ_EN_SYSTEM :: "SYSTEM"
IQ_EN_LEVEL :: "LEVEL"
IQ_EN_EXIT :: "EXIT"
IQ_EN_FAILED :: "FAILED"
IQ_EN_POINT :: "POINT"
IQ_EN_DRAW :: "DRAW"
IQ_EN_PRESS_START :: "PRESS START"
IQ_EN_CONTROLLER :: "CONTROLLER"
IQ_EN_CONTINUE_PROMPT :: "CONTINUE?"
IQ_EN_YES :: "YES"
IQ_EN_NO :: "NO"
IQ_EN_RESUME :: "RESUME"
IQ_EN_START_OVER :: "START OVER"
IQ_EN_QUIT :: "QUIT"
IQ_EN_QUIT_PROMPT :: "QUIT?"
IQ_EN_START_OVER_PROMPT :: "START OVER?"
IQ_EN_SCORE :: "SCORE"
IQ_EN_IQ :: "I.Q"
IQ_EN_PAUSE :: "PAUSE"
IQ_EN_NOW_LOADING :: "NOW LOADING"
IQ_EN_STAGE_COMPLETE :: "STAGE COMPLETE"
IQ_EN_GAME_OVER :: "GAME OVER"
IQ_EN_IQ_RANKING :: "I.Q RANKING"
IQ_EN_RANKING_RETURN :: "START / X: RETURN"
IQ_EN_NAME_ENTRY :: "NAME ENTRY"
IQ_EN_SPACE :: "SP"
IQ_EN_BACKSPACE :: "BS"
IQ_EN_END :: "END"
IQ_EN_MEMORY_CARD :: "MEMORY CARD"
IQ_EN_SAVE_DATA :: "SAVE DATA"
IQ_EN_PRESS_SAVE :: "PRESS X TO SAVE"
IQ_EN_PLAYER :: "PLAYER"
IQ_EN_PRESS_EXIT :: "PRESS X TO EXIT"
IQ_EN_DATA_SAVED :: "DATA SAVED"
IQ_EN_DATA_LOADED :: "DATA LOADED"
IQ_EN_WAVE_START :: "WAVE START"
IQ_EN_PLAYER_1 :: "PLAYER 1"
IQ_EN_PLAYER_2 :: "PLAYER 2"
IQ_EN_FORBIDDEN :: "FORBIDDEN CUBE!"
IQ_EN_MISSED :: "MISSED!"
IQ_EN_PERFECT :: "PERFECT!  5000 POINT BONUS"
IQ_EN_MULTIPLE_HITS :: "MULTIPLE HITS"

IQ_EN_FMT_STRING :: "%s"
IQ_EN_FMT_LEVEL :: "%d"
IQ_EN_FMT_PLAYER_RESULT :: "PLAYER %d  %s"
IQ_EN_FMT_TWO_PLAYER_SCORE :: "P1  %02d        P2  %02d"
IQ_EN_FMT_PLAYER_WINS :: "PLAYER %d WINS"
IQ_EN_FMT_MATCH_SCORE :: "%02d  -  %02d"
IQ_EN_FMT_CAMERA :: "CAMERA  %d"
IQ_EN_FMT_SCORE :: "%08d"
IQ_EN_FMT_IQ_VALUE :: "%03d"
IQ_EN_FMT_PLAYER_1_SCORE :: "P1 %02d"
IQ_EN_FMT_PLAYER_2_SCORE :: "P2 %02d"
IQ_EN_FMT_STAGE :: "STAGE %d"
IQ_EN_FMT_WAVE_WIDTH :: "WAVE 1    WIDTH %d"
IQ_EN_FMT_STAGE_SCORE :: "STAGE SCORE  %08d"
IQ_EN_FMT_IQ :: "I.Q  %03d"
IQ_EN_FMT_FINAL_SCORE :: "FINAL SCORE  %08d"
IQ_EN_FMT_NAME :: "%c%c%c%c%c%c%c%c%c%c"
IQ_EN_FMT_RANK :: "%2d"
IQ_EN_FMT_RANKING_IQ :: "IQ %03d"
IQ_EN_FMT_PERCENT :: "%3d"
IQ_EN_FMT_TEXTURE :: "TEXTURE %02d"
IQ_EN_FMT_GROUP :: "GROUP NO     %03d"
IQ_EN_FMT_DIMENSIONS :: "X= %d     Z= %d"

IQ_EN_RULE_LABELS := [7]string{
	"BASIC RULES", "FORBIDDEN CUBE", "ADVANTAGE CUBE",
	"DEMO 1", "DEMO 2", "DEMO 3", IQ_EN_EXIT,
}
IQ_EN_CONTROLLER_LABELS := [6]string{
	"TO MARK", "TO CAPTURE", "TO BOMB", "TO ACCELERATE", "DEFAULT", IQ_EN_EXIT,
}
IQ_EN_BUTTON_NAMES := [4]string{"CROSS", "CIRCLE", "SQUARE", "TRIANGLE"}
IQ_EN_OPTIONS_LABELS := [10]string{
	IQ_EN_CONTROLLER, "GAME MODE", "RANKING", IQ_EN_MEMORY_CARD, "TEXTURE",
	IQ_EN_PLAYER, "MUSIC", "SOUND", "INVERTED", IQ_EN_EXIT,
}
IQ_EN_EDITOR_ACTIONS := [7]string{"CLS", "COPY", "PASTE", "LOAD", "SAVE", "PLAY", IQ_EN_EXIT}
IQ_EN_EDITOR_SIZE_HELP :: "TAB: SIZE   PGUP/PGDN: GROUP"
IQ_EN_EDITOR_CYCLE_HELP :: "Z: CYCLE   X: NORMAL   C: CLS"
IQ_EN_OFF :: "OFF"
IQ_EN_ON :: "ON"
IQ_EN_CHARACTER_NAMES := [3]string{"Eliot", "Cynthia", "Spike"}
IQ_EN_MODE_NAMES := [2]string{IQ_EN_NORMAL, IQ_EN_ORIGINAL}
IQ_EN_NAME_CHARACTERS :: "ABCDEFGHIJKLMNOPQRSTUVWXYZ.,-?"
IQ_EN_FMT_STATUS :: "STAGE %d  WAVE %d  SCORE %08d"
IQ_EN_WINDOW_TITLE :: "I.Q: Intelligent Qube"
